import sqlalchemy as sa

from alembic import op

from lib.util_datetime import tzware_datetime
from lib.util_sqlalchemy import AwareDateTime


"""
add foobar column to users

Revision ID: 05e33d1d147b
Revises: 78a03d9c1a0c
Create Date: 2017-08-28 09:33:57.480614
"""

# Revision identifiers, used by Alembic.
revision = '05e33d1d147b'
down_revision = '78a03d9c1a0c'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
